homepage:
  path: /
  controller: App\Controller\PortfolioController::index

navbar:
  path: /navbar
  controller: App\Controller\PortfolioController::navbar

bootstrap:
  path: /bootstrap
  controller: App\Controller\PortfolioController::bootstrap

php:
  path: /php
  controller: App\Controller\PortfolioController::php

javascript:
  path: /javascript
  controller: App\Controller\PortfolioController::javascript

symfony:
  path: /symfony
  controller: App\Controller\PortfolioController::symfony

wordpress:
  path: /wordpress
  controller: App\Controller\PortfolioController::wordpress

projet_bootstrap:
  path: /projet_bootstrap
  controller: App\Controller\PortfolioController::projet_bootstrap

projet_javascript:
  path: /projet_javascript
  controller: App\Controller\PortfolioController::projet_javascript

projet_php:
  path: /projet_php
  controller: App\Controller\PortfolioController::projet_php

projet_symfony:
  path: /projet_symfony
  controller: App\Controller\PortfolioController::projet_symfony

projet_wordpress:
  path: /projet_wordpress
  controller: App\Controller\PortfolioController::projet_wordpress